CREATE TABLE invoice(
id VARCHAR(36) NOT NULL PRIMARY KEY,
pedido_id VARCHAR(36) NOT NULL UNIQUE REFERENCES pedido(id),
tipo VARCHAR(10) NOT NULL,
chave VARCHAR(50),
status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
created_at TIMESTAMP NOT NULL DEFAULT now(),
updated_at TIMESTAMP NOT NULL DEFAULT now()
);
